SENDGRID_USERNAME: carolyntestingcode
SENDGRID_PASSWORD: codetesting
MY_SUPER_SECRET_VARIABLE: secret123456

STRIPE_PUBLISHABLE_KEY: pk_test_jPbsyahUzCWf9t2E8ABT9Eby
STRIPE_SECRET_KEY: sk_test_pjNLvT9uDy9OmGfIGthHj0nZ
